// Hookploy main <-> edge protocol (PRD §7). One bidirectional stream; the
// edge is the client and dials out, so edges need no inbound port.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: proto/hookploy/v1/hookploy.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Hookploy_Session_FullMethodName = "/hookploy.v1.Hookploy/Session"
)

// HookployClient is the client API for Hookploy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HookployClient interface {
	Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[EdgeMessage, MainMessage], error)
}

type hookployClient struct {
	cc grpc.ClientConnInterface
}

func NewHookployClient(cc grpc.ClientConnInterface) HookployClient {
	return &hookployClient{cc}
}

func (c *hookployClient) Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[EdgeMessage, MainMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Hookploy_ServiceDesc.Streams[0], Hookploy_Session_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EdgeMessage, MainMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Hookploy_SessionClient = grpc.BidiStreamingClient[EdgeMessage, MainMessage]

// HookployServer is the server API for Hookploy service.
// All implementations must embed UnimplementedHookployServer
// for forward compatibility.
type HookployServer interface {
	Session(grpc.BidiStreamingServer[EdgeMessage, MainMessage]) error
	mustEmbedUnimplementedHookployServer()
}

// UnimplementedHookployServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHookployServer struct{}

func (UnimplementedHookployServer) Session(grpc.BidiStreamingServer[EdgeMessage, MainMessage]) error {
	return status.Error(codes.Unimplemented, "method Session not implemented")
}
func (UnimplementedHookployServer) mustEmbedUnimplementedHookployServer() {}
func (UnimplementedHookployServer) testEmbeddedByValue()                  {}

// UnsafeHookployServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HookployServer will
// result in compilation errors.
type UnsafeHookployServer interface {
	mustEmbedUnimplementedHookployServer()
}

func RegisterHookployServer(s grpc.ServiceRegistrar, srv HookployServer) {
	// If the following call panics, it indicates UnimplementedHookployServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Hookploy_ServiceDesc, srv)
}

func _Hookploy_Session_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HookployServer).Session(&grpc.GenericServerStream[EdgeMessage, MainMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Hookploy_SessionServer = grpc.BidiStreamingServer[EdgeMessage, MainMessage]

// Hookploy_ServiceDesc is the grpc.ServiceDesc for Hookploy service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Hookploy_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hookploy.v1.Hookploy",
	HandlerType: (*HookployServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Session",
			Handler:       _Hookploy_Session_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/hookploy/v1/hookploy.proto",
}
