// Hookploy main <-> edge protocol (PRD §7). One bidirectional stream; the
// edge is the client and dials out, so edges need no inbound port.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/hookploy/v1/hookploy.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// edge → main
type EdgeMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*EdgeMessage_Hello
	//	*EdgeMessage_Update
	Msg           isEdgeMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EdgeMessage) Reset() {
	*x = EdgeMessage{}
	mi := &file_proto_hookploy_v1_hookploy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EdgeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeMessage) ProtoMessage() {}

func (x *EdgeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hookploy_v1_hookploy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeMessage.ProtoReflect.Descriptor instead.
func (*EdgeMessage) Descriptor() ([]byte, []int) {
	return file_proto_hookploy_v1_hookploy_proto_rawDescGZIP(), []int{0}
}

func (x *EdgeMessage) GetMsg() isEdgeMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *EdgeMessage) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Msg.(*EdgeMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *EdgeMessage) GetUpdate() *ExecUpdate {
	if x != nil {
		if x, ok := x.Msg.(*EdgeMessage_Update); ok {
			return x.Update
		}
	}
	return nil
}

type isEdgeMessage_Msg interface {
	isEdgeMessage_Msg()
}

type EdgeMessage_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type EdgeMessage_Update struct {
	Update *ExecUpdate `protobuf:"bytes,2,opt,name=update,proto3,oneof"`
}

func (*EdgeMessage_Hello) isEdgeMessage_Msg() {}

func (*EdgeMessage_Update) isEdgeMessage_Msg() {}

// Hello is the first message of a session: the edge authenticates itself.
// The server name is derived from the token's subject (edges are zero-config:
// --main + --token only); when `server` is set it must match that subject.
// Anything else as first message closes the stream.
type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        string                 `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`   // optional identity assertion
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`     // plaintext server token (hps_...)
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"` // edge binary version
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_proto_hookploy_v1_hookploy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hookploy_v1_hookploy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_proto_hookploy_v1_hookploy_proto_rawDescGZIP(), []int{1}
}

func (x *Hello) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *Hello) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Hello) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// ExecUpdate streams execution progress back to main.
type ExecUpdate struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	// Types that are valid to be assigned to Event:
	//
	//	*ExecUpdate_OpStart
	//	*ExecUpdate_OpEnd
	//	*ExecUpdate_Log
	//	*ExecUpdate_Done
	Event         isExecUpdate_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecUpdate) Reset() {
	*x = ExecUpdate{}
	mi := &file_proto_hookploy_v1_hookploy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecUpdate) ProtoMessage() {}

func (x *ExecUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hookploy_v1_hookploy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecUpdate.ProtoReflect.Descriptor instead.
func (*ExecUpdate) Descriptor() ([]byte, []int) {
	return file_proto_hookploy_v1_hookploy_proto_rawDescGZIP(), []int{2}
}

func (x *ExecUpdate) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ExecUpdate) GetEvent() isExecUpdate_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ExecUpdate) GetOpStart() *OpStart {
	if x != nil {
		if x, ok := x.Event.(*ExecUpdate_OpStart); ok {
			return x.OpStart
		}
	}
	return nil
}

func (x *ExecUpdate) GetOpEnd() *OpEnd {
	if x != nil {
		if x, ok := x.Event.(*ExecUpdate_OpEnd); ok {
			return x.OpEnd
		}
	}
	return nil
}

func (x *ExecUpdate) GetLog() *LogChunk {
	if x != nil {
		if x, ok := x.Event.(*ExecUpdate_Log); ok {
			return x.Log
		}
	}
	return nil
}

func (x *ExecUpdate) GetDone() *ExecDone {
	if x != nil {
		if x, ok := x.Event.(*ExecUpdate_Done); ok {
			return x.Done
		}
	}
	return nil
}

type isExecUpdate_Event interface {
	isExecUpdate_Event()
}

type ExecUpdate_OpStart struct {
	OpStart *OpStart `protobuf:"bytes,2,opt,name=op_start,json=opStart,proto3,oneof"`
}

type ExecUpdate_OpEnd struct {
	OpEnd *OpEnd `protobuf:"bytes,3,opt,name=op_end,json=opEnd,proto3,oneof"`
}

type ExecUpdate_Log struct {
	Log *LogChunk `protobuf:"bytes,4,opt,name=log,proto3,oneof"`
}

type ExecUpdate_Done struct {
	Done *ExecDone `protobuf:"bytes,5,opt,name=done,proto3,oneof"`
}

func (*ExecUpdate_OpStart) isExecUpdate_Event() {}

func (*ExecUpdate_OpEnd) isExecUpdate_Event() {}

func (*ExecUpdate_Log) isExecUpdate_Event() {}

func (*ExecUpdate_Done) isExecUpdate_Event() {}

type OpStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpStart) Reset() {
	*x = OpStart{}
	mi := &file_proto_hookploy_v1_hookploy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpStart) ProtoMessage() {}

func (x *OpStart) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hookploy_v1_hookploy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpStart.ProtoReflect.Descriptor instead.
func (*OpStart) Descriptor() ([]byte, []int) {
	return file_proto_hookploy_v1_hookploy_proto_rawDescGZIP(), []int{3}
}

func (x *OpStart) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *OpStart) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type OpEnd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ExitCode      *int32                 `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3,oneof" json:"exit_code,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpEnd) Reset() {
	*x = OpEnd{}
	mi := &file_proto_hookploy_v1_hookploy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpEnd) ProtoMessage() {}

func (x *OpEnd) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hookploy_v1_hookploy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpEnd.ProtoReflect.Descriptor instead.
func (*OpEnd) Descriptor() ([]byte, []int) {
	return file_proto_hookploy_v1_hookploy_proto_rawDescGZIP(), []int{4}
}

func (x *OpEnd) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *OpEnd) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OpEnd) GetExitCode() int32 {
	if x != nil && x.ExitCode != nil {
		return *x.ExitCode
	}
	return 0
}

func (x *OpEnd) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type LogChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Stream        string                 `protobuf:"bytes,2,opt,name=stream,proto3" json:"stream,omitempty"` // stdout | stderr | system
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogChunk) Reset() {
	*x = LogChunk{}
	mi := &file_proto_hookploy_v1_hookploy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogChunk) ProtoMessage() {}

func (x *LogChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hookploy_v1_hookploy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogChunk.ProtoReflect.Descriptor instead.
func (*LogChunk) Descriptor() ([]byte, []int) {
	return file_proto_hookploy_v1_hookploy_proto_rawDescGZIP(), []int{5}
}

func (x *LogChunk) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *LogChunk) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *LogChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// ExecDone is the terminal update of one execution.
type ExecDone struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Digest        string                 `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"` // digest the engine pinned (rollout promotion on wave 1)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecDone) Reset() {
	*x = ExecDone{}
	mi := &file_proto_hookploy_v1_hookploy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecDone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecDone) ProtoMessage() {}

func (x *ExecDone) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hookploy_v1_hookploy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecDone.ProtoReflect.Descriptor instead.
func (*ExecDone) Descriptor() ([]byte, []int) {
	return file_proto_hookploy_v1_hookploy_proto_rawDescGZIP(), []int{6}
}

func (x *ExecDone) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ExecDone) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ExecDone) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

// main → edge
type MainMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*MainMessage_Ack
	//	*MainMessage_Exec
	//	*MainMessage_Cancel
	Msg           isMainMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MainMessage) Reset() {
	*x = MainMessage{}
	mi := &file_proto_hookploy_v1_hookploy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MainMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MainMessage) ProtoMessage() {}

func (x *MainMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hookploy_v1_hookploy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MainMessage.ProtoReflect.Descriptor instead.
func (*MainMessage) Descriptor() ([]byte, []int) {
	return file_proto_hookploy_v1_hookploy_proto_rawDescGZIP(), []int{7}
}

func (x *MainMessage) GetMsg() isMainMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *MainMessage) GetAck() *HelloAck {
	if x != nil {
		if x, ok := x.Msg.(*MainMessage_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *MainMessage) GetExec() *Execution {
	if x != nil {
		if x, ok := x.Msg.(*MainMessage_Exec); ok {
			return x.Exec
		}
	}
	return nil
}

func (x *MainMessage) GetCancel() *CancelExec {
	if x != nil {
		if x, ok := x.Msg.(*MainMessage_Cancel); ok {
			return x.Cancel
		}
	}
	return nil
}

type isMainMessage_Msg interface {
	isMainMessage_Msg()
}

type MainMessage_Ack struct {
	Ack *HelloAck `protobuf:"bytes,1,opt,name=ack,proto3,oneof"`
}

type MainMessage_Exec struct {
	Exec *Execution `protobuf:"bytes,2,opt,name=exec,proto3,oneof"`
}

type MainMessage_Cancel struct {
	Cancel *CancelExec `protobuf:"bytes,3,opt,name=cancel,proto3,oneof"` // reserved, not implemented in v1
}

func (*MainMessage_Ack) isMainMessage_Msg() {}

func (*MainMessage_Exec) isMainMessage_Msg() {}

func (*MainMessage_Cancel) isMainMessage_Msg() {}

type HelloAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MainVersion   string                 `protobuf:"bytes,1,opt,name=main_version,json=mainVersion,proto3" json:"main_version,omitempty"`
	Server        string                 `protobuf:"bytes,2,opt,name=server,proto3" json:"server,omitempty"` // the server name main resolved from the token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloAck) Reset() {
	*x = HelloAck{}
	mi := &file_proto_hookploy_v1_hookploy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloAck) ProtoMessage() {}

func (x *HelloAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hookploy_v1_hookploy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloAck.ProtoReflect.Descriptor instead.
func (*HelloAck) Descriptor() ([]byte, []int) {
	return file_proto_hookploy_v1_hookploy_proto_rawDescGZIP(), []int{8}
}

func (x *HelloAck) GetMainVersion() string {
	if x != nil {
		return x.MainVersion
	}
	return ""
}

func (x *HelloAck) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

// Execution carries everything the edge needs: the edge is stateless, ops
// arrive fully interpolated as the same JSON snapshot main persists.
type Execution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"` // deploy | task
	Service       string                 `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	Instance      string                 `protobuf:"bytes,4,opt,name=instance,proto3" json:"instance,omitempty"`
	Dir           string                 `protobuf:"bytes,5,opt,name=dir,proto3" json:"dir,omitempty"`
	Image         string                 `protobuf:"bytes,6,opt,name=image,proto3" json:"image,omitempty"`                    // service image declaration, "" if none
	Digest        string                 `protobuf:"bytes,7,opt,name=digest,proto3" json:"digest,omitempty"`                  // rollout-resolved digest, "" = resolve from :latest
	OpsJson       []byte                 `protobuf:"bytes,8,opt,name=ops_json,json=opsJson,proto3" json:"ops_json,omitempty"` // []ops.Step JSON
	TimeoutMs     int64                  `protobuf:"varint,9,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Execution) Reset() {
	*x = Execution{}
	mi := &file_proto_hookploy_v1_hookploy_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Execution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Execution) ProtoMessage() {}

func (x *Execution) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hookploy_v1_hookploy_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Execution.ProtoReflect.Descriptor instead.
func (*Execution) Descriptor() ([]byte, []int) {
	return file_proto_hookploy_v1_hookploy_proto_rawDescGZIP(), []int{9}
}

func (x *Execution) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *Execution) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Execution) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *Execution) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *Execution) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

func (x *Execution) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Execution) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *Execution) GetOpsJson() []byte {
	if x != nil {
		return x.OpsJson
	}
	return nil
}

func (x *Execution) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type CancelExec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelExec) Reset() {
	*x = CancelExec{}
	mi := &file_proto_hookploy_v1_hookploy_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelExec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelExec) ProtoMessage() {}

func (x *CancelExec) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hookploy_v1_hookploy_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelExec.ProtoReflect.Descriptor instead.
func (*CancelExec) Descriptor() ([]byte, []int) {
	return file_proto_hookploy_v1_hookploy_proto_rawDescGZIP(), []int{10}
}

func (x *CancelExec) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

var File_proto_hookploy_v1_hookploy_proto protoreflect.FileDescriptor

const file_proto_hookploy_v1_hookploy_proto_rawDesc = "" +
	"\n" +
	" proto/hookploy/v1/hookploy.proto\x12\vhookploy.v1\"s\n" +
	"\vEdgeMessage\x12*\n" +
	"\x05hello\x18\x01 \x01(\v2\x12.hookploy.v1.HelloH\x00R\x05hello\x121\n" +
	"\x06update\x18\x02 \x01(\v2\x17.hookploy.v1.ExecUpdateH\x00R\x06updateB\x05\n" +
	"\x03msg\"O\n" +
	"\x05Hello\x12\x16\n" +
	"\x06server\x18\x01 \x01(\tR\x06server\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"\xf0\x01\n" +
	"\n" +
	"ExecUpdate\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x121\n" +
	"\bop_start\x18\x02 \x01(\v2\x14.hookploy.v1.OpStartH\x00R\aopStart\x12+\n" +
	"\x06op_end\x18\x03 \x01(\v2\x12.hookploy.v1.OpEndH\x00R\x05opEnd\x12)\n" +
	"\x03log\x18\x04 \x01(\v2\x15.hookploy.v1.LogChunkH\x00R\x03log\x12+\n" +
	"\x04done\x18\x05 \x01(\v2\x15.hookploy.v1.ExecDoneH\x00R\x04doneB\a\n" +
	"\x05event\"3\n" +
	"\aOpStart\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"w\n" +
	"\x05OpEnd\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\texit_code\x18\x03 \x01(\x05H\x00R\bexitCode\x88\x01\x01\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05errorB\f\n" +
	"\n" +
	"_exit_code\"L\n" +
	"\bLogChunk\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x16\n" +
	"\x06stream\x18\x02 \x01(\tR\x06stream\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"H\n" +
	"\bExecDone\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x16\n" +
	"\x06digest\x18\x03 \x01(\tR\x06digest\"\xa0\x01\n" +
	"\vMainMessage\x12)\n" +
	"\x03ack\x18\x01 \x01(\v2\x15.hookploy.v1.HelloAckH\x00R\x03ack\x12,\n" +
	"\x04exec\x18\x02 \x01(\v2\x16.hookploy.v1.ExecutionH\x00R\x04exec\x121\n" +
	"\x06cancel\x18\x03 \x01(\v2\x17.hookploy.v1.CancelExecH\x00R\x06cancelB\x05\n" +
	"\x03msg\"E\n" +
	"\bHelloAck\x12!\n" +
	"\fmain_version\x18\x01 \x01(\tR\vmainVersion\x12\x16\n" +
	"\x06server\x18\x02 \x01(\tR\x06server\"\xf2\x01\n" +
	"\tExecution\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x18\n" +
	"\aservice\x18\x03 \x01(\tR\aservice\x12\x1a\n" +
	"\binstance\x18\x04 \x01(\tR\binstance\x12\x10\n" +
	"\x03dir\x18\x05 \x01(\tR\x03dir\x12\x14\n" +
	"\x05image\x18\x06 \x01(\tR\x05image\x12\x16\n" +
	"\x06digest\x18\a \x01(\tR\x06digest\x12\x19\n" +
	"\bops_json\x18\b \x01(\fR\aopsJson\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\t \x01(\x03R\ttimeoutMs\"/\n" +
	"\n" +
	"CancelExec\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId2M\n" +
	"\bHookploy\x12A\n" +
	"\aSession\x12\x18.hookploy.v1.EdgeMessage\x1a\x18.hookploy.v1.MainMessage(\x010\x01B*Z(github.com/reorx/hookploy/internal/pb;pbb\x06proto3"

var (
	file_proto_hookploy_v1_hookploy_proto_rawDescOnce sync.Once
	file_proto_hookploy_v1_hookploy_proto_rawDescData []byte
)

func file_proto_hookploy_v1_hookploy_proto_rawDescGZIP() []byte {
	file_proto_hookploy_v1_hookploy_proto_rawDescOnce.Do(func() {
		file_proto_hookploy_v1_hookploy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_hookploy_v1_hookploy_proto_rawDesc), len(file_proto_hookploy_v1_hookploy_proto_rawDesc)))
	})
	return file_proto_hookploy_v1_hookploy_proto_rawDescData
}

var file_proto_hookploy_v1_hookploy_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_hookploy_v1_hookploy_proto_goTypes = []any{
	(*EdgeMessage)(nil), // 0: hookploy.v1.EdgeMessage
	(*Hello)(nil),       // 1: hookploy.v1.Hello
	(*ExecUpdate)(nil),  // 2: hookploy.v1.ExecUpdate
	(*OpStart)(nil),     // 3: hookploy.v1.OpStart
	(*OpEnd)(nil),       // 4: hookploy.v1.OpEnd
	(*LogChunk)(nil),    // 5: hookploy.v1.LogChunk
	(*ExecDone)(nil),    // 6: hookploy.v1.ExecDone
	(*MainMessage)(nil), // 7: hookploy.v1.MainMessage
	(*HelloAck)(nil),    // 8: hookploy.v1.HelloAck
	(*Execution)(nil),   // 9: hookploy.v1.Execution
	(*CancelExec)(nil),  // 10: hookploy.v1.CancelExec
}
var file_proto_hookploy_v1_hookploy_proto_depIdxs = []int32{
	1,  // 0: hookploy.v1.EdgeMessage.hello:type_name -> hookploy.v1.Hello
	2,  // 1: hookploy.v1.EdgeMessage.update:type_name -> hookploy.v1.ExecUpdate
	3,  // 2: hookploy.v1.ExecUpdate.op_start:type_name -> hookploy.v1.OpStart
	4,  // 3: hookploy.v1.ExecUpdate.op_end:type_name -> hookploy.v1.OpEnd
	5,  // 4: hookploy.v1.ExecUpdate.log:type_name -> hookploy.v1.LogChunk
	6,  // 5: hookploy.v1.ExecUpdate.done:type_name -> hookploy.v1.ExecDone
	8,  // 6: hookploy.v1.MainMessage.ack:type_name -> hookploy.v1.HelloAck
	9,  // 7: hookploy.v1.MainMessage.exec:type_name -> hookploy.v1.Execution
	10, // 8: hookploy.v1.MainMessage.cancel:type_name -> hookploy.v1.CancelExec
	0,  // 9: hookploy.v1.Hookploy.Session:input_type -> hookploy.v1.EdgeMessage
	7,  // 10: hookploy.v1.Hookploy.Session:output_type -> hookploy.v1.MainMessage
	10, // [10:11] is the sub-list for method output_type
	9,  // [9:10] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_hookploy_v1_hookploy_proto_init() }
func file_proto_hookploy_v1_hookploy_proto_init() {
	if File_proto_hookploy_v1_hookploy_proto != nil {
		return
	}
	file_proto_hookploy_v1_hookploy_proto_msgTypes[0].OneofWrappers = []any{
		(*EdgeMessage_Hello)(nil),
		(*EdgeMessage_Update)(nil),
	}
	file_proto_hookploy_v1_hookploy_proto_msgTypes[2].OneofWrappers = []any{
		(*ExecUpdate_OpStart)(nil),
		(*ExecUpdate_OpEnd)(nil),
		(*ExecUpdate_Log)(nil),
		(*ExecUpdate_Done)(nil),
	}
	file_proto_hookploy_v1_hookploy_proto_msgTypes[4].OneofWrappers = []any{}
	file_proto_hookploy_v1_hookploy_proto_msgTypes[7].OneofWrappers = []any{
		(*MainMessage_Ack)(nil),
		(*MainMessage_Exec)(nil),
		(*MainMessage_Cancel)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_hookploy_v1_hookploy_proto_rawDesc), len(file_proto_hookploy_v1_hookploy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_hookploy_v1_hookploy_proto_goTypes,
		DependencyIndexes: file_proto_hookploy_v1_hookploy_proto_depIdxs,
		MessageInfos:      file_proto_hookploy_v1_hookploy_proto_msgTypes,
	}.Build()
	File_proto_hookploy_v1_hookploy_proto = out.File
	file_proto_hookploy_v1_hookploy_proto_goTypes = nil
	file_proto_hookploy_v1_hookploy_proto_depIdxs = nil
}
