// Package views holds the templ templates of the web UI and their view
// models. *_templ.go files are generated by scripts/gentempl.sh and
// committed, so plain `go build` never needs the templ CLI.
package views

import (
	"fmt"
	"time"
)

// ServerChip is one server in the topbar status strip.
type ServerChip struct {
	Name    string
	Online  bool
	Local   bool
	Version string
}

// Crumb is one breadcrumb segment; empty Href renders as plain text.
type Crumb struct {
	Label string
	Href  string
}

// Ago renders a compact relative time ("12s", "3m", "2h", "5d").
func Ago(t time.Time) string {
	d := time.Since(t)
	switch {
	case d < time.Minute:
		return fmt.Sprintf("%ds", int(d.Seconds()))
	case d < time.Hour:
		return fmt.Sprintf("%dm", int(d.Minutes()))
	case d < 24*time.Hour:
		return fmt.Sprintf("%dh", int(d.Hours()))
	default:
		return fmt.Sprintf("%dd", int(d.Hours()/24))
	}
}

// Elapsed renders the duration between start and end (or now when end is
// nil), compact: "8s", "1m12s", "2h3m".
func Elapsed(start time.Time, end *time.Time) string {
	to := time.Now()
	if end != nil {
		to = *end
	}
	d := to.Sub(start)
	if d < 0 {
		d = 0
	}
	switch {
	case d < time.Minute:
		return fmt.Sprintf("%ds", int(d.Seconds()))
	case d < time.Hour:
		return fmt.Sprintf("%dm%02ds", int(d.Minutes()), int(d.Seconds())%60)
	default:
		return fmt.Sprintf("%dh%02dm", int(d.Hours()), int(d.Minutes())%60)
	}
}

// ShortDigest compacts "sha256:abcdef..." to "abcdef012345" (12 hex chars).
func ShortDigest(digest string) string {
	s := digest
	if i := len("sha256:"); len(s) > i && s[:i] == "sha256:" {
		s = s[i:]
	}
	if len(s) > 12 {
		s = s[:12]
	}
	return s
}
