// Package views holds the templ templates of the web UI and their view
// models. *_templ.go files are generated by scripts/gentempl.sh and
// committed, so plain `go build` never needs the templ CLI.
package views

import (
	"fmt"
	"time"
)

// ServerChip is one server in the topbar status strip.
type ServerChip struct {
	Name    string
	Online  bool
	Local   bool
	Version string
}

// Crumb is one breadcrumb segment; empty Href renders as plain text.
type Crumb struct {
	Label string
	Href  string
}

// DashboardData feeds the dashboard's three sections.
type DashboardData struct {
	Active   []ActiveDeploy
	Services []ServiceRow
	Recent   []DeployRow
}

// ActiveDeploy is one in-progress deploy card.
type ActiveDeploy struct {
	ID        string
	Service   string
	Kind      string // "deploy" | "task:<name>"
	Status    string
	Wave      int // 1-based current wave
	Waves     int
	CreatedAt time.Time
	Execs     []ExecLine
}

// ExecLine is one execution inside an active card.
type ExecLine struct {
	Instance string
	Server   string
	Status   string
	Wave     int
}

// ServiceRow is one row of the service list.
type ServiceRow struct {
	Name       string
	Webhook    bool
	Servers    []string
	LastID     string
	LastStatus string // empty when the service never deployed
	LastAt     time.Time
}

// DeployRow is one row of the recent-deploys list and service history.
type DeployRow struct {
	ID        string
	Service   string
	Kind      string
	Status    string
	Digest    string
	CreatedAt time.Time
	Duration  string // "—" when not applicable (superseded/queued)
}

// ServicePage feeds the service detail page.
type ServicePage struct {
	Name    string
	Image   string
	Webhook bool
	Timeout string
	Waves   [][]InstanceCard // rollout topology: waves × instances
	Deploy  []StepView
	Tasks   []TaskView
	History []DeployRow
}

// InstanceCard is one instance inside the rollout topology.
type InstanceCard struct {
	Name   string
	Server string
	Dir    string
	Online bool
}

// StepView is one pipeline step with its args flattened for display.
type StepView struct {
	Op   string
	Args []KV
}

// KV is one rendered argument.
type KV struct {
	K, V string
}

// TaskView is one named task pipeline.
type TaskView struct {
	Name  string
	Steps []StepView
}

// DeployPage feeds the deploy detail page.
type DeployPage struct {
	ID        string
	Service   string
	Kind      string
	Status    string
	Error     string
	Digest    string // short form
	CreatedAt time.Time
	Duration  string
	Payload   string // pretty-printed JSON, "" when trivial
	Terminal  bool
	Waves     []WaveView
	Execs     []ExecOption            // filter dropdown
	ExecMap   map[string]ExecMapEntry // for logs.js prefixes and anchors
}

// WaveView is one wave of the execution timeline.
type WaveView struct {
	Index int // 1-based
	Execs []ExecView
}

// ExecView is one execution block inside the timeline.
type ExecView struct {
	ID       string
	Instance string
	Server   string
	Dir      string
	Status   string
	Error    string
	Duration string
	Ops      []OpView
}

// OpView is one op row of an execution.
type OpView struct {
	Index    int
	Name     string
	Duration string
	ExitCode string // "" when the op spawned no process
	Error    string
}

// ExecOption is one entry of the log execution filter.
type ExecOption struct {
	ID    string
	Label string
}

// ExecMapEntry tells logs.js how to label frames of one execution.
type ExecMapEntry struct {
	Instance string            `json:"instance"`
	Ops      map[string]string `json:"ops"` // op index (decimal string) → op name
}

// KindLabel renders a deploy's kind: "deploy" or "task:<name>".
func KindLabel(kind, task string) string {
	if task != "" {
		return kind + ":" + task
	}
	return kind
}

// Clock renders a compact absolute time for list rows.
func Clock(t time.Time) string {
	return t.Local().Format("01-02 15:04")
}

// Ago renders a compact relative time ("12s", "3m", "2h", "5d").
func Ago(t time.Time) string {
	d := time.Since(t)
	switch {
	case d < time.Minute:
		return fmt.Sprintf("%ds", int(d.Seconds()))
	case d < time.Hour:
		return fmt.Sprintf("%dm", int(d.Minutes()))
	case d < 24*time.Hour:
		return fmt.Sprintf("%dh", int(d.Hours()))
	default:
		return fmt.Sprintf("%dd", int(d.Hours()/24))
	}
}

// Elapsed renders the duration between start and end (or now when end is
// nil), compact: "8s", "1m12s", "2h3m".
func Elapsed(start time.Time, end *time.Time) string {
	to := time.Now()
	if end != nil {
		to = *end
	}
	d := to.Sub(start)
	if d < 0 {
		d = 0
	}
	switch {
	case d < time.Minute:
		return fmt.Sprintf("%ds", int(d.Seconds()))
	case d < time.Hour:
		return fmt.Sprintf("%dm%02ds", int(d.Minutes()), int(d.Seconds())%60)
	default:
		return fmt.Sprintf("%dh%02dm", int(d.Hours()), int(d.Minutes())%60)
	}
}

// ShortDigest compacts "sha256:abcdef..." to "abcdef012345" (12 hex chars).
func ShortDigest(digest string) string {
	s := digest
	if i := len("sha256:"); len(s) > i && s[:i] == "sha256:" {
		s = s[i:]
	}
	if len(s) > 12 {
		s = s[:12]
	}
	return s
}
